const top100Films = [
  { title:' Amsterdam '},
{ title:' Ankara '},
{ title:' Athens '},
{ title:' Atlantic City '},
{ title:' Baltimore '},
{ title:' Bangkok '},
{ title:' Beijing '},
{ title:' Berlin '},
{ title:' Berne '},
{ title:' Brussels '},
{ title:' Budapest '},
{ title:' Buenos Aires '},
{ title:' Cairo '},
{ title:' Canberra '},
{ title:' Cannes '},
{ title:' Cape Town '},
{ title:' Chicago '},
{ title:' Cologne '},
{ title:' Copenhagen '},
{ title:' Damascus '},
{ title:' Delhi '},
{ title:' Dubai City '},
{ title:' Dublin '},
{ title:' Florence'},
{ title:' Genève '},
{ title:' Hague '},
{ title:' Ha Noi '},
{ title:' Havana '},
{ title:' Helsinki '},
{ title:' HongKong '},
{ title:' Honolulu '},
{ title:' Istanbul '},
{ title:' Jakarta '},
{ title:' Jerusalem '},
{ title:' Kansas City '},
{ title:' Kathmandu '},
{ title:' KualaLumpur '},
{ title:' Lisbon '},
{ title:' London '},
{ title:' Los Angeles '},
{ title:' Luxembourg '},
{ title:' Madrid '},
{ title:' Manila '},
{ title:' Melbourne '},
{ title:' MexicoCity '},
{ title:' Milan '},
{ title:' Montreal '},
{ title:' Moscow '},
{ title:' Mumbai '},
{ title:' Munich '},
{ title:' Nazareth '},
{ title:' New York '},
{ title:' Nice '},
{ title:' Osaka '},
{ title:' Ottawa '},
{ title:' Oslo '},
{ title:' Paris '},
{ title:' Philadelphia '},
{ title:' PhnomPenh '},
{ title:' Prague '},
{ title:' Quito '},
{ title:' Reykjavik '},
{ title:' Riode Janeiro '},
{ title:' San Francisco '},
{ title:' Santa Fe '},
{ title:' Santiago '},
{ title:' SãoPaulo '},
{ title:' Shanghai '},
{ title:' Singapore City '},
{ title:' Stockholm '},
{ title:' Saint Petersburg '},
{ title:' Sydney '},
{ title:' Taipei '},
{ title:' Tokyo '},
{ title:' Venice '},
{ title:' Vienna '},
{ title:' Washington '},
{ title:' Zürich '},

   
  ];

  export default top100Films